spring.application.name=todo
server.port=8080

# 요청/응답 한글 처리
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# JSP 수정 시 서버 재시작 없이 바로 반영
server.servlet.jsp.init-parameters.development=true
